# Generated by Django 6.0.6 on 2026-06-18 14:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used for login.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate a login without touching the person record or any historical data.')),
                ('is_staff', models.BooleanField(default=False, help_text="Grants access to the Django Admin site. Not part of the app's own per-congregation RBAC (Phase 3) -- reserved for platform-operator use, never set for ordinary congregation users.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
