# Generated by Django 6.0.6 on 2026-06-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text="A person's contact email -- distinct from users.email, which only exists if they also log in.", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('membership_status', models.CharField(choices=[('member', 'Member'), ('visitor', 'Visitor'), ('regular_attender', 'Regular Attender'), ('inactive', 'Inactive')], default='visitor', max_length=30)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Soft lifecycle flag. See deletion policy: a person is only hard-deletable once nothing references them.')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "The Smith Family"', max_length=150)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
                ('primary_contact_person', models.ForeignKey(blank=True, help_text='Who mail/communications address by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_for_households', to='people.person')),
            ],
            options={
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='PersonHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_role', models.CharField(blank=True, choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('other', 'Other')], help_text='Per-relationship, since the same person can hold a different role in each household.', max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Which household is the 'main' one for this person.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='people.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_links', to='people.person')),
            ],
            options={
                'db_table': 'person_households',
                'constraints': [models.UniqueConstraint(fields=('person', 'household'), name='uniq_person_household'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='uniq_primary_household_per_person')],
            },
        ),
    ]
