# Generated by Django 6.0.6 on 2026-06-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('read_only', 'Read Only'), ('canceled', 'Canceled')], max_length=20)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text="Display-only (e.g. 'your subscription ends on [date]') -- the access gate keys off `status`, not this field, since Stripe doesn't end a subscription early just because cancellation was requested.")),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='tenancy.congregation')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('stripe_webhook', 'Stripe Webhook'), ('admin_action', 'Admin Action')], max_length=20)),
                ('stripe_event_id', models.CharField(blank=True, help_text='For idempotency -- Stripe can redeliver the same webhook.', max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(help_text="When the event actually happened (set explicitly by the caller -- the Stripe event's own `created` timestamp for webhook-sourced rows, or timezone.now() for admin actions), not when this row was inserted -- webhooks can be retried or delayed, so the two aren't the same thing.")),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
            ],
            options={
                'db_table': 'subscription_events',
                'ordering': ['-occurred_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_event_id__isnull', False)), fields=('stripe_event_id',), name='uniq_subscription_event_stripe_event_id')],
            },
        ),
    ]
