# Generated by Django 6.0.6 on 2026-06-18 14:07

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(help_text='IANA timezone name, needed to correctly interpret service/schedule/attendance timestamps.', max_length=50, validators=[apps.tenancy.models.validate_timezone])),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('size_category', models.CharField(blank=True, help_text="e.g. '1-50', '51-200' -- optional, for onboarding personalization.", max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, help_text="The single source of truth for ownership -- this is what's actually checked anywhere 'is this the owner?' matters (billing, account deletion, transferring ownership), not a count of Owner-role assignments. Nullable only to break the creation-order circular dependency; the application always sets this immediately after creating a congregation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_congregations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'congregations',
            },
        ),
    ]
