# Generated by Django 6.0.6 on 2026-06-19 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_retired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CongregationModuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='Not null, PROTECT -- an audit trail must never silently lose who made the change.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='module_system.module')),
            ],
            options={
                'verbose_name_plural': 'congregation module history',
                'db_table': 'congregation_module_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CongregationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.congregation')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, help_text="Nullable audit attribution -- losing the user shouldn't block the row from existing.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='congregation_modules', to='module_system.module')),
            ],
            options={
                'db_table': 'congregation_modules',
                'constraints': [models.UniqueConstraint(fields=('congregation', 'module'), name='uniq_congregation_module')],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='module_system.module')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='module_system.module')),
            ],
            options={
                'db_table': 'module_dependencies',
                'constraints': [models.UniqueConstraint(fields=('module', 'depends_on_module'), name='uniq_module_dependency'), models.CheckConstraint(condition=models.Q(('module', models.F('depends_on_module')), _negated=True), name='module_dependency_not_self')],
            },
        ),
    ]
